In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/Monali/OneDrive/Desktop/FBS/Data analysis/datasets/student_10.csv")
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

In [4]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [5]:
df['Class']== 12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [6]:
df[df['Class']==12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [7]:
df[df['Percentage']>50]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
df['Student ID']== 1008.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Student ID, dtype: bool

In [9]:
df[df['Student ID']==1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [10]:
df.loc[df['Student ID']== 1008.0,'Percentage'] =92

In [11]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        92.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

## concat

In [12]:
df1=pd.DataFrame({'id':[101,102,103],'name':['rohan','karan','parth']})
df1

    id   name
0  101  rohan
1  102  karan
2  103  parth

In [13]:
df2=pd.DataFrame({'dept_id':[1,2,1],'dname':['admin','It','admin']})
df2

   dept_id  dname
0        1  admin
1        2     It
2        1  admin

In [14]:
pd.concat([df1, df2],axis=1)

    id   name  dept_id  dname
0  101  rohan        1  admin
1  102  karan        2     It
2  103  parth        1  admin

In [15]:
pd.concat([df1,df2])

      id   name  dept_id  dname
0  101.0  rohan      NaN    NaN
1  102.0  karan      NaN    NaN
2  103.0  parth      NaN    NaN
0    NaN    NaN      1.0  admin
1    NaN    NaN      2.0     It
2    NaN    NaN      1.0  admin

## merge

In [19]:
emp=pd.DataFrame({'id':[101,102,103,104],'name':['rohan','karan','parth','rohit'],'did':[1,2,1,4]})
emp

    id   name  did
0  101  rohan    1
1  102  karan    2
2  103  parth    1
3  104  rohit    4

In [20]:
dept=pd.DataFrame({'dept_id':[1,2,3],'dname':['admin','IT','sales']})
dept

   dept_id  dname
0        1  admin
1        2     IT
2        3  sales

In [25]:
pd.merge(emp,dept,how='inner',left_on='did', right_on='dept_id')

    id   name  did  dept_id  dname
0  101  rohan    1        1  admin
1  102  karan    2        2     IT
2  103  parth    1        1  admin

In [26]:
pd.merge(emp,dept,how='left',left_on='did', right_on='dept_id')

    id   name  did  dept_id  dname
0  101  rohan    1      1.0  admin
1  102  karan    2      2.0     IT
2  103  parth    1      1.0  admin
3  104  rohit    4      NaN    NaN

In [27]:
pd.merge(emp,dept,how='right',left_on='did', right_on='dept_id')

      id   name  did  dept_id  dname
0  101.0  rohan  1.0        1  admin
1  103.0  parth  1.0        1  admin
2  102.0  karan  2.0        2     IT
3    NaN    NaN  NaN        3  sales

In [28]:
pd.merge(emp,dept,left_on='did', right_on='dept_id')

    id   name  did  dept_id  dname
0  101  rohan    1        1  admin
1  102  karan    2        2     IT
2  103  parth    1        1  admin